function Line = LineSpec(LineNumber,LineType)
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here
switch LineType
    case 'line'
        LineTypes={'b-'...
            ,'r--'...
            ,'g:'...
            ,'m:d'...
            ,'c-.'...
            ,'b-*'...
            ,'r.-s'...
            ,'g--o'};
    case 'marker'
        LineTypes={'bo'...
            ,'rs'...
            ,'cd'...
            ,'g*'...
            ,'bt'};
end
Line=LineTypes{LineNumber};
end

